development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: pg_games_development
  username: howardchen
  password:

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: pg_games_test
  username: howardchen
  password:
